kind: pipeline
name: backend

steps:
  - name: install
    image: node
    volumes:
      - name: node_modules
        path: /backend/node_modules
    commands:
      - cd backend
      - yarn
      - yarn build

  - name: build
    image: node
    volumes:
      - name: node_modules
        path: /backend/node_modules
    commands:
      - cd backend
      - yarn build

  - name: docker
    image: plugins/docker
    settings:
      repo: ukita/dinero-api
      auto_tag: true
      context: backend/
      dockerfile: backend/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

volumes:
  - name: node_modules
    temp: {}
